tasks:
  - name: Gitpod Phoenix
    init: |
      docker-compose -f docker-compose.yml pull
    command: |
      docker-compose -f docker-compose.yml up --no-start
      docker-compose -f docker-compose.yml start db
      docker-compose -f docker-compose.yml run --service-ports app bash

ports:
  - port: 4000
    onOpen: open-browser
  - port: 5432
    onOpen: ignore

github:
  prebuilds:
    master: true
    branches: true
    pullRequests: true
    pullRequestsFromForks: true
    addCheck: true
    addComment: true
    addBadge: false

vscode:
  extensions:
    - elixir-lsp.elixir-ls
